---
- name: export kubeconfig
  shell: rm -rf $HOME/.kube/ && mkdir -p $HOME/.kube && cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && chown $(id -u):$(id -g) $HOME/.kube/config


- name: apply weave deploy
  shell: kubectl apply -f "{{ weave_url }}"

- name: capture join command
  shell: cat output.txt  | grep -A 1 "kubeadm join"
  register: join_command

- name: set fact to use it in worker nodes
  set_fact:
      join_command: "{{ join_command }}"
  delegate_to: localhost
  delegate_facts: yes
  run_once: yes

- name: check value for join command
  debug:
    var: hostvars['localhost']['join_command'].stdout